//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ElasticSearchVSSQLServer.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ElasticSearchVSSQLServer.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA is already enabled for this account..
        /// </summary>
        public static string _2FAEnabledAlready {
            get {
                return ResourceManager.GetString("2FAEnabledAlready", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string _Empty_1_ {
            get {
                return ResourceManager.GetString("_Empty[1]", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data aktive e qasjes është jashtë intervalit.
        /// </summary>
        public static string ActiveMembershipDateRequired {
            get {
                return ResourceManager.GetString("ActiveMembershipDateRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Formati i lejuar është: {0}.
        /// </summary>
        public static string AllowedFileFormatsDocuments {
            get {
                return ResourceManager.GetString("AllowedFileFormatsDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të paktën një email dështoi.
        /// </summary>
        public static string AtLeastOneEmailFailed {
            get {
                return ResourceManager.GetString("AtLeastOneEmailFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Llogaria juaj është bllokuar. Ju lutemi shikoni emailin për të vazhduar me procesin e zbllokimin.
        /// </summary>
        public static string AttemptToLogin {
            get {
                return ResourceManager.GetString("AttemptToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivendosja e aplikacionit Authenticator.
        /// </summary>
        public static string AuthenticatorAppReseted {
            get {
                return ResourceManager.GetString("AuthenticatorAppReseted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Çelësi i autentifikuesit nuk u gjet.
        /// </summary>
        public static string AuthenticatorKeyNotFound {
            get {
                return ResourceManager.GetString("AuthenticatorKeyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk mund ta dekriptoni çelësin.
        /// </summary>
        public static string CouldNotDecryptKey {
            get {
                return ResourceManager.GetString("CouldNotDecryptKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi aktual nuk është i saktë.
        /// </summary>
        public static string CurrentPasswordIsNotCorrect {
            get {
                return ResourceManager.GetString("CurrentPasswordIsNotCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Të dhënat nuk janë gjetur.
        /// </summary>
        public static string DataNotFound {
            get {
                return ResourceManager.GetString("DataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duhet të konfirmoni llogarinë përmes emailit tuaj.
        /// </summary>
        public static string EmailNotConfirmed {
            get {
                return ResourceManager.GetString("EmailNotConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-i u dërgua me sukses..
        /// </summary>
        public static string EmailSent {
            get {
                return ResourceManager.GetString("EmailSent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email-i u dërgua me sukses.
        /// </summary>
        public static string EmailSentSuccessfully {
            get {
                return ResourceManager.GetString("EmailSentSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Entiteti nuk ekziston..
        /// </summary>
        public static string EntityDoesntExist {
            get {
                return ResourceManager.GetString("EntityDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndodhi gabim.
        /// </summary>
        public static string ErrorOccurred {
            get {
                return ResourceManager.GetString("ErrorOccurred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ky përdorues tashmë ka një konfigurim ekzistues të pamjes..
        /// </summary>
        public static string ExistingViewConfiguration {
            get {
                return ResourceManager.GetString("ExistingViewConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ka ndodhur një gabim gjatë ruajtjes së të dhënave.
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Këto urdhërpagesa jane konfirmuar me parë..
        /// </summary>
        public static string HasBeenConfirmBefore {
            get {
                return ResourceManager.GetString("HasBeenConfirmBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Në sistem kemi vetëm 3 gjuhë!.
        /// </summary>
        public static string infoLanguageLimit {
            get {
                return ResourceManager.GetString("infoLanguageLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi i 2FA është i pavlefshëm.
        /// </summary>
        public static string Invalid2FACode {
            get {
                return ResourceManager.GetString("Invalid2FACode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kodi i pavlefshëm. Ju lutemi provoni përsëri..
        /// </summary>
        public static string InvalidCode {
            get {
                return ResourceManager.GetString("InvalidCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Domeni nuk është valid ose ka skaduar.
        /// </summary>
        public static string InvalidDomain {
            get {
                return ResourceManager.GetString("InvalidDomain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format i çelësit është i pavlefshëm.
        /// </summary>
        public static string InvalidKeyFormat {
            get {
                return ResourceManager.GetString("InvalidKeyFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi nuk përputhet me formatin e kërkuar.
        /// </summary>
        public static string InvalidPasswordFormat {
            get {
                return ResourceManager.GetString("InvalidPasswordFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk lejohet ndryshimi i rolit ose rolit të palejuar..
        /// </summary>
        public static string InvalidRoleOrRoleChangeNotAllowed {
            get {
                return ResourceManager.GetString("InvalidRoleOrRoleChangeNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {senderName} është bashkangjitur..
        /// </summary>
        public static string JoinedChat {
            get {
                return ResourceManager.GetString("JoinedChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {senderName} është larguar..
        /// </summary>
        public static string LeftChat {
            get {
                return ResourceManager.GetString("LeftChat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shumë përpjekje të dështuara. Provo përsëri më vonë..
        /// </summary>
        public static string LockedEntry {
            get {
                return ResourceManager.GetString("LockedEntry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Emaili ose fjalëkalimi është gabim.
        /// </summary>
        public static string LoginError {
            get {
                return ResourceManager.GetString("LoginError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjatësia maksimale për këtë fushë është {1}.
        /// </summary>
        public static string MaxLength {
            get {
                return ResourceManager.GetString("MaxLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gjatësia minimale për këtë fushë është {1}.
        /// </summary>
        public static string MinLength {
            get {
                return ResourceManager.GetString("MinLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kode të reja të gjeneruara.
        /// </summary>
        public static string NewGeneratedCodes {
            get {
                return ResourceManager.GetString("NewGeneratedCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk u gjetën role për këtë përdorues..
        /// </summary>
        public static string NoRolesFoundForThisUser {
            get {
                return ResourceManager.GetString("NoRolesFoundForThisUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri nuk mund të jetë i njëjtë me fjalëkalimin e mëparshëm..
        /// </summary>
        public static string NotSamePasswordAsPrevious {
            get {
                return ResourceManager.GetString("NotSamePasswordAsPrevious", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndryshimi i fjalëkalimit dështoi.
        /// </summary>
        public static string PasswordChangedFailed {
            get {
                return ResourceManager.GetString("PasswordChangedFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi u ndryshua me sukses.
        /// </summary>
        public static string PasswordChangedSuccess {
            get {
                return ResourceManager.GetString("PasswordChangedSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi juaj është rivendosur me sukses..
        /// </summary>
        public static string PasswordHasBeenResetSuccessfully {
            get {
                return ResourceManager.GetString("PasswordHasBeenResetSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi i ri dhe fjalëkalimi i konfirmimit nuk përputhen..
        /// </summary>
        public static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rivendosja e fjalëkalimit dështoi.
        /// </summary>
        public static string PasswordResetFailed {
            get {
                return ResourceManager.GetString("PasswordResetFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fjalëkalimi u rivendos me sukses.
        /// </summary>
        public static string PasswordResetSuccess {
            get {
                return ResourceManager.GetString("PasswordResetSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vetëm pagesat e konfirmuara/rimbursuara më parë..
        /// </summary>
        public static string PaymentsPreviouslyConfirmed {
            get {
                return ResourceManager.GetString("PaymentsPreviouslyConfirmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pagesat gati për konfirmim.
        /// </summary>
        public static string PaymentsReadyForConfirmation {
            get {
                return ResourceManager.GetString("PaymentsReadyForConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Numri personal duhet të ketë të paktën 10 karaktere..
        /// </summary>
        public static string PersonalNumberAtLeast10Characters {
            get {
                return ResourceManager.GetString("PersonalNumberAtLeast10Characters", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesi me këtë numër personal ekziston.
        /// </summary>
        public static string personalNumberExists {
            get {
                return ResourceManager.GetString("personalNumberExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju lutemi plotësoni numrin personal.
        /// </summary>
        public static string PersonalNumberisRequired {
            get {
                return ResourceManager.GetString("PersonalNumberisRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fotografia e profilit nuk u gjet.
        /// </summary>
        public static string ProfileImageNotFound {
            get {
                return ResourceManager.GetString("ProfileImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Raporti.
        /// </summary>
        public static string Report {
            get {
                return ResourceManager.GetString("Report", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fushë obligative.
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nuk është gjetur asnjë e dhënë me këta parametra të kërkimit.
        /// </summary>
        public static string ResourceNotFound {
            get {
                return ResourceManager.GetString("ResourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qasja në rol u fshi me sukses..
        /// </summary>
        public static string RoleAccessDeletedSuccessfully {
            get {
                return ResourceManager.GetString("RoleAccessDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Komunikimi me server ka dështuar.
        /// </summary>
        public static string ServerNoContact {
            get {
                return ResourceManager.GetString("ServerNoContact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disa urdhërpagesa janë konfirmuar më parë..
        /// </summary>
        public static string SomePaymentsConfirmedBefore {
            get {
                return ResourceManager.GetString("SomePaymentsConfirmedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabela nuk ekziston..
        /// </summary>
        public static string TableDoesntExist {
            get {
                return ResourceManager.GetString("TableDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Konfigurimi i temës nuk u gjet..
        /// </summary>
        public static string ThemeConfigurationNotFound {
            get {
                return ResourceManager.GetString("ThemeConfigurationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2FA nuk është i aktivizuar.
        /// </summary>
        public static string TwoFactorNotEnabled {
            get {
                return ResourceManager.GetString("TwoFactorNotEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verifikimi 2FA i suksesshëm. 2FA tani është aktivizuar..
        /// </summary>
        public static string TwoFactorVerificationSuccessful {
            get {
                return ResourceManager.GetString("TwoFactorVerificationSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkohet 2FA. Ju lutemi verifikoni kodin..
        /// </summary>
        public static string TwoFARequired {
            get {
                return ResourceManager.GetString("TwoFARequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fletëpagesat nuk përputhen. Nuk mund të bëhet barazimi i tyre.
        /// </summary>
        public static string UncompletedInvoice {
            get {
                return ResourceManager.GetString("UncompletedInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Qasja e përdoruesit u fshi me sukses..
        /// </summary>
        public static string UserAccessDeletedSuccessfully {
            get {
                return ResourceManager.GetString("UserAccessDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesii është bllokuar deri në momentin që klikoni në linkun që do i&apos;u vije në email per ndyshimin e fjalëkalimit.
        /// </summary>
        public static string UserBlocked {
            get {
                return ResourceManager.GetString("UserBlocked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kërkohet UserId dhe NewRoleName..
        /// </summary>
        public static string UserIdAndNewRoleNameAreRequired {
            get {
                return ResourceManager.GetString("UserIdAndNewRoleNameAreRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyrja e përdoruesit u krye me sukses.
        /// </summary>
        public static string UserLoginSuccessfully {
            get {
                return ResourceManager.GetString("UserLoginSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Perdoruesi nuk u gjet.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Përdoruesi ose fotografia e profilit nuk u gjet.
        /// </summary>
        public static string UserOrProfileImageNotFound {
            get {
                return ResourceManager.GetString("UserOrProfileImageNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roli i përdoruesit ndryshoi me sukses!.
        /// </summary>
        public static string UserRoleChangedSuccessfully {
            get {
                return ResourceManager.GetString("UserRoleChangedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ju lutem, zgjedhni një gjuhë të vlefshme nga lista..
        /// </summary>
        public static string ValueOutRangeLanguageID {
            get {
                return ResourceManager.GetString("ValueOutRangeLanguageID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ndodhi një gabim gjatë krijimit të konfigurimit të pamjes për këtë përdorues.
        /// </summary>
        public static string ViewConfigurationCreationError {
            get {
                return ResourceManager.GetString("ViewConfigurationCreationError", resourceCulture);
            }
        }
    }
}
